# Generated by Django 5.2.5 on 2025-10-27 20:39

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to=accounts.utils.user_picture_upload_to
            ),
        ),
    ]
