# Generated by Django 5.2.5 on 2025-09-29 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoanalysis",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
