# Generated by Django 5.2.5 on 2025-10-02 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Substance",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name_en", models.CharField(max_length=100, unique=True)),
                (
                    "name_pl",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="videoanalysis",
            name="confidence_scores",
        ),
        migrations.RemoveField(
            model_name="videoanalysis",
            name="results",
        ),
        migrations.AddField(
            model_name="videoanalysis",
            name="title",
            field=models.CharField(default="Untitled", max_length=255),
        ),
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("confidence_score", models.FloatField()),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_results",
                        to="analysis.videoanalysis",
                    ),
                ),
                (
                    "substance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detection_results",
                        to="analysis.substance",
                    ),
                ),
            ],
            options={
                "unique_together": {("analysis", "substance")},
            },
        ),
    ]
