# Generated by Django 5.2.5 on 2025-10-02 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_substance_remove_videoanalysis_confidence_scores_and_more'),
    ]

    operations = [
    ]
