# Generated by Django 5.2.5 on 2025-10-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20251002_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoanalysis',
            name='thumbnail_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='videoanalysis',
            name='thumbnail_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
