# Generated by Django 5.2.5 on 2025-10-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0004_videoanalysis_thumbnail_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoanalysis",
            name="thumbnail_file",
            field=models.FileField(blank=True, null=True, upload_to="thumbnails/"),
        ),
    ]
