# Generated by Django 5.2.5 on 2025-10-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0005_videoanalysis_thumbnail_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videoanalysis",
            name="thumbnail_file",
        ),
        migrations.RemoveField(
            model_name="videoanalysis",
            name="thumbnail_name",
        ),
        migrations.RemoveField(
            model_name="videoanalysis",
            name="thumbnail_path",
        ),
        migrations.RemoveField(
            model_name="videoanalysis",
            name="video_file_path",
        ),
        migrations.RemoveField(
            model_name="videoanalysis",
            name="video_name",
        ),
        migrations.AddField(
            model_name="videoanalysis",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="thumbnails/"),
        ),
        migrations.AddField(
            model_name="videoanalysis",
            name="video",
            field=models.FileField(default="videos/default.mp4", upload_to="videos/"),
            preserve_default=False,
        ),
    ]
