# Generated by Django 5.2.5 on 2025-10-27 20:39

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0006_remove_videoanalysis_thumbnail_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videoanalysis",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to=accounts.utils.user_thumbnail_upload_to
            ),
        ),
        migrations.AlterField(
            model_name="videoanalysis",
            name="video",
            field=models.FileField(upload_to=accounts.utils.user_video_upload_to),
        ),
    ]
