# Generated by Django 5.2.5 on 2025-11-12 10:47

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0007_alter_videoanalysis_thumbnail_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videoanalysis",
            name="video",
            field=models.FileField(
                blank=True, null=True, upload_to=accounts.utils.user_video_upload_to
            ),
        ),
    ]
