# Generated by Django 5.2.5 on 2025-11-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0008_alter_videoanalysis_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoanalysis",
            name="error_message",
            field=models.TextField(
                blank=True, help_text="Error details when analysis fails", null=True
            ),
        ),
    ]
