# Generated by Django 5.2.5 on 2025-11-21 18:58

import accounts.utils
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0010_add_polish_translations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videoanalysis",
            name="video",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=accounts.utils.user_video_upload_to,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["mp4"]
                    )
                ],
            ),
        ),
    ]
