# Generated by Django 5.2.5 on 2025-11-24 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0011_videoanalysis_patient_alter_videoanalysis_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videoanalysis",
            name="title",
        ),
        migrations.AddField(
            model_name="videoanalysis",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
