# Generated by Django 5.2.5 on 2025-11-27 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analysis", "0012_remove_videoanalysis_title_videoanalysis_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoanalysis",
            name="patient_guid",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                null=True,
            ),
        ),
    ]
