# Generated by Django 5.2.5 on 2025-11-24 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="document_id",
            field=models.CharField(
                db_index=True, default="TEMP", max_length=20, unique=True
            ),
            preserve_default=False,
        ),
    ]
